### ISSUE TITLE
Create Attack Roll Macro damage expression parsing bug

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#81] opened 2020-07-08 16:48 UTC
When using "Create Attack Roll Macro" from the DNDBeyond.mtmacset, the Damage Dice Expression needs to be able to take multiple names and types.

For example 2d8 + 3 piercing + 2d6 poison

Currently, it appears to be "parsed" into "2d8" and "3 piercing + 2d6 poison" and that latter the "bonus" is compared to zero

```
Invalid condition in IF(bonus > 0) roll option.
       Statement options (if any): h, if (bonus > 0)
       Statement Body : rollString = baseRoll + " + " + bonus; rollString = baseRoll
```

**Comment by trey-kirk-sp** [comment] 2020-07-08 16:50
Dupe of Issue #31 where, in addition to specify critable status of damage, we'll be able to also specify multiple extra damage

**Closed by trey-kirk-sp** 2020-07-08 16:50 UTC

**Comment by trey-kirk-sp** [comment] 2020-07-13 14:13
Something that wasn't made explicitly clear here: the new "Attack Editor" deprecates "Create Attack Roll Macro". So #31 will not actually fix Create Attack Roll Macro, but instead replace it with a more comprehensive macro, hence marking it duped.
